### ISSUE TITLE
[Tendermint/tm-bench] - Very slow transaction rate with 4 validators

### ISSUE THREAD

**Issue by rahulltkr** [tendermint/tools#61]
Hi , @melekes  

I have configured Tendermint with 4 validators on AWS instances (c4.xlarge) with following configuration. 

CPU: 4
RAM: 7.5G

The setup is configured as [defined here](https://tendermint.readthedocs.io/en/master/using-tendermint.html#adding-a-validator). After that started Tendermint on all machines with dummy app using all 4 validators with p2p.seeds as following command.

`tendermint node --proxy_app=dummy --p2p.seeds=172.31.4.103:46656,172.31.5.122:46656,172.31.8.55:46656,172.31.15.61:46656`

Now uses tm-bench tool from one machine. While using less transactions it processed successfully. When I use 10000 transactions. The tm-bench command finish in 5-10 seconds but all validators still showing transactions in log and completed approx in 5 minutes. So all of them performing very slow... 

`tm-bench -T 5 -r 10000 -c 1 127.0.0.1:46657`

https://www.screencast.com/t/w3IAKHLfCm6

Please suggest - if I am doing anything in wrong way? Is there anyway to speedup transactions?  What server specs and configuration required to run 1million transactions?

**Comment by Greg-Szabo** [comment]
Hi @rahulltkr ,
If you're using the dummy app and you want to test the speed of the network, it's better to make a few changes on the tendermint config. The changes I used to do performance testing are documented in the config.toml template used in ansible, here: https://github.com/tendermint/tools/blob/master/ansible/roles/config/templates/config.toml.j2

Look at the part below "if service == 'tendermint'", those settings will give you much better performance. I'm still trying to tweak the best settings for best performance with an application, so feel free to play around with them. Note that if you're using "memdb" as the database backend, it will only store data while the process is running. If you restart the testnet, it will give you database corruption errors, since the data was not saved to disk. (The "leveldb" backend will save it the data.)

We are still working on improving the performance of testnets so the settings will definitely change later.

Also, make sure you are testing the testnet for an extensive time. My default execution of `tm-bench` is 300 seconds (5 minutes). The reason for this is twofold:
1. The statistics generated by `tm-bench` uses exponential moving average calculations which gets better precision over time. You could also use `tm-monitor` which gives you a better point-in-time status of the network but you have to monitor it manually.
2. Unfortunately `tm-bench` exits right after sending out all the transactions over the time period. (It uses async transactions.) If the network is overloaded, some (maybe even a lot) of the transactions will not be processed yet and `tm-bench` will give you lower statistics.

Regards,
Greg

**Comment by rahulltkr** [comment]
Hi @Greg-Szabo 

I have used configuration given here https://github.com/tendermint/tools/blob/master/ansible/roles/config/templates/config.toml.j2  and Also upgraded all validators to CPU:8, RAM:15G. But still facing issue with 10000 transactions/sec.  Transactions were running very slow, also one validator shows multiples errors like below

https://www.screencast.com/t/vRWiZmMPS

It tooks approx 20-25 minutes to complete the tm-bench command.  The tm-bench command was 

`tm-bench -T 20 -r 10000 -c 4 127.0.0.1:46657`

**Comment by melekes** [comment]
> If the network is overloaded, some (maybe even a lot) of the transactions will not be processed yet and tm-bench will give you lower statistics.

That's fine. we should not include transactions that have been processed after `tm-bench (TimeStart, TimeEnd)`.

**Comment by melekes** [comment]
@rahulltkr thank you for testing this! We appreciate the input.

> What server specs and configuration required to run 1million transactions?

Why do you need 1 million transactions? 

There is no such configuration to my knowledge. Moreover, no existing blockchain/tech can process 1 million transactions per second. Maybe except some DAG based blockchains.

Tendermint currently can process thousands of transactions (depending on the block size and the number of validators). We're working on making it even faster though.

**Comment by ValarDragon** [comment]
Closing this issue for now. Txs going through after tm-bench finishes is intended behavour. (Though this should be partially alleviated by #110)
