### ISSUE TITLE
[tm-monitor] docker container of tendermint monitor connection refused

### ISSUE THREAD

**Issue by yunkunrao** [tendermint/tools#92]
Follow the steps in README, i.e.:

```
docker run -it --rm -v "/tmp:/tendermint" tendermint/tendermint init
docker run -it --rm -v "/tmp:/tendermint" -p "46657:46657" --name=tm tendermint/tendermint

docker run -it --rm --link=tm tendermint/monitor tm:46657
```

there's a connection refused issue for the monitor, here's the log detail:

```
root@ubuntu18:/home/ryk/go_home/src/github.com/tendermint/tendermint/DOCKER# docker run -it --rm --link=tm tendermint/monitor tm:46657
panic: dial tcp 172.17.0.2:46657: getsockopt: connection refused

goroutine 1 [running]:
main.startMonitor(0x7ffcff9abe1a, 0x8, 0x6)
        /go/src/github.com/tendermint/tools/tm-monitor/main.go:79 +0x3dc
main.main()
        /go/src/github.com/tendermint/tools/tm-monitor/main.go:53 +0x16b
```

Is there something wrong with environment? Thanks.

**Comment by yunkunrao** [comment]
BY adding "node --proxy-app=XX" subcmd, this issue was fixed. So do you have any plan about updating README?
By the way, there's tm-monitor build failure with latest commit on master branch. Could you help double confirm about this? Thanks very much.

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/1538

**Comment by yunkunrao** [comment]
I have the workaround and give comments for [tendermint/tendermint#1538](https://github.com/tendermint/tendermint/issues/1538). And thanks for your reply.

**Comment by LilithVL** [comment]
Can confirm the tm-monitor build failure.

**Comment by yunkunrao** [comment]
Hi, @LilithVL, go get this tool repo and dep ensure will fix build errors and it works at least in my env. :blush:

**Comment by melekes** [comment]
@yunkunrao @LilithVL sorry for confusion! fixed by https://github.com/tendermint/tools/commit/399c7ea8edc6d950e3aeb2b006e73552e4427134

Re build failure: execute `make get_vendor_deps`
Re `node --proxy-app=XX`: this is only needed if you don't have an ABCI app (by default tendermint probes `tcp://127.0.0.1:46658` for ABCI application). If you don't have an app, you can use `kvstore`: `node --proxy_app=kvstore`. If you have and it's running somewhere else, again point tendermint to the right location: `node --proxy_app=tcp://{IP}:{Port}` or `node --proxy_app=unix://{IP}:{Port}`
